# Generated by Django 4.1.7 on 2023-03-31 12:48

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_room_alter_myuser_profile_picture_roomuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='profile picture',
            field=models.FileField(blank=True, upload_to='', verbose_name=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=-1, scale=None, size=[200, 300], upload_to='')),
        ),
    ]
