# Generated by Django 4.1.7 on 2023-03-31 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_rename_profile picture_myuser_file_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='file_field',
        ),
    ]
