# Generated by Django 4.1.7 on 2023-03-12 21:55

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_myuser_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='profile_picture',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to=''),
        ),
    ]
